import { cn } from '@/lib/utils';
import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Oleo_Script } from 'next/font/google'

const font = Roboto({ subsets: ['latin'], weight: ["400", "700"] })
const titleFont = Oleo_Script({ subsets: ['latin'], weight: '700', variable: "--font-header" });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("flex flex-col", titleFont.variable, font.className)}>
        {children}
      </body>
    </html>
  )
}
